WIP: Added templates
ithillel-php-basic/php-basic-2-637e11275b1a8b3b40bcd7d3 pull request #4
Opened 2023-05-08 09:56 UTC by KhOlga

2023-05-08 11:32 UTC, alexpalyan requested changes

2023-05-08 11:32 UTC, alexpalyan commented on index.php
> +$layout = renderTemplate('main.php', [
Я гадаю, тут краще буде підключити layout.php шаблон )

2023-05-08 11:55 UTC, KhOlga commented on index.php
> +  echo $count;
Виправила

2023-05-08 11:55 UTC, KhOlga commented on index.php
> +$layout = renderTemplate('main.php', [
Виправила

2023-05-11 06:23 UTC, alexpalyan approved these changes

2023-05-11 06:23 UTC, merged